name: ChunkSteal
version: '${version}'
main: io.github.zirlak.chunksteal.ChunkSteal
api-version: '1.20'
commands:
  buychunk:
    description: Buys a chunk
    usage: /<command>
  normalaxe:
    description: Gives you a normal axe
  specialaxe:
    description: Gives you a special axe
  map:
    description: Gives you a map